from __future__ import division, print_function
import numpy as np

#
#
#
def ao_log_hartree(ao, method=None):
  """
    Computes radial parts of Hartree potentials generated by the radial orbitals
    Args: 
      self: class instance of ao_log_c
    Result:
      ao_pot with respective radial parts
  """
  ao_hartree = deepcopy(ao)
  
  return ao_hartree
  


if __name__ == '__main__':
  from pyscf.nao.m_system_vars import system_vars_c
  
